### PR TITLE
Updated typescript and babel to support new ts features

### PR DESCRIPTION
**Pull request by keeslinp**
What it says on the tin

### CODE REVIEW

**Review by mdlavin — APPROVED** [review]

**Review by IevgenRagulin — DISMISSED** [review]

**Comment by DavidTanner** [comment]
The failures might be because of a change to the LocalStack tag?  I can't remember if the project is still using `:latest`

**Comment by IevgenRagulin** [comment]
> The failures might be because of a change to the LocalStack tag? I can't remember if the project is still using `:latest`

It doesn't look like we are using `latest` in this project:
https://github.com/lifeomic/lambda-tools/blob/410385d70985d6c771158b5a8d4df6750397b623/test/localstack/lambdaSetup.test.js#L15
https://github.com/lifeomic/lambda-tools/blob/d5d9dcb8b77f9d295f9358af2d99bd049bb13c24/test/utils/kinesisTools.test.js#L14

**Comment by DavidTanner** [comment]
I wish docker tags were static.  They recently updated the lambci tag for nodejs10.x
https://github.com/lifeomic/lambda-tools/pull/223

**Review by mdlavin — APPROVED** [review]

**Review by mdlavin — APPROVED** [review]

**Comment by DavidTanner** [comment]
I think the only way to retrigger the `pr` build is by pushing some kind of commit.  Maybe just merge with master

**Review by tqhoughton — DISMISSED** [review]

**Comment by IevgenRagulin** [comment]
> I think the only way to retrigger the `pr` build is by pushing some kind of commit. Maybe just merge with master
Merged master in

**Review by IevgenRagulin — APPROVED** [review]

**Pull request merged**
